config/routes.rb
Rails.application.routes.draw do
  resources :characteristic_values
  resources :weights
  resources :part_of_characteristics
  resources :people
  resources :characteristics
  resources :information_systems do
    collection do
      get :main
    end
  end
  resources :addresses
  get 'welcome/load_from_json', as: :lfj
  root :to => 'information_systems#main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
  belongs_to :information_system
  belongs_to :address
  has_many :part_of_characteristics


  validates :name, presence: true
  validates :type_of_data,  presence: true
  validates :result_type,  presence: true

end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1
  # PATCH/PUT /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: 'Characteristic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_params
      params.require(:characteristic).permit(:name, :information_system_id, :type_of_data, :result_type, :address_id)
    end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.haml
= form_for @characteristic do |f|
  - if @characteristic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@characteristic.errors.count, "error")} prohibited this characteristic from being saved:"
      %ul
        - @characteristic.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-3.col-centre
      = f.label :name
    .col-md-6.col-centre
      = f.text_field :name
  .row
    .col-md-3.col-centre
      = f.label :information_system
    .col-md-6.col-centre
      = f.text_field :information_system_id
  .row
    .col-md-3.col-centre
      = f.label :type_of_data
    .col-md-6.col-centre
      = f.number_field :type_of_data
  .row
    .col-md-3.col-centre
      = f.label :result_type
    .col-md-6.col-centre
      = f.number_field :result_type
  .row
    .col-md-3.col-centre
      = f.label :address
    .col-md-6.col-centre
      = f.text_field :address_id
  .my-hr
    %hr
  .row
    .col-md-6.col-centre
      = f.submit t('helpers.submit.submit'), class: "btn btn-primary buttons"

app/views/characteristics/edit.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.characteristics.edit')

= render 'form'

.row
  .col-md-3.col-centre
    = link_to t('helpers.submit.back'), characteristics_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre
    = link_to t('helpers.submit.show'), @characteristic, class: "btn btn-primary buttons"

app/views/characteristics/index.html.haml
%table.table-striped.table-hover.table-style
  %caption.new-obj
    = link_to new_characteristic_path, class: 'btn btn-primary' do
      = fa_icon :plus
      = t('buttons.new.characteristics')
  %thead.table-head
    %tr
      %th= Characteristic.human_attribute_name(:name)
      %th= Characteristic.human_attribute_name(:information_system)
      %th= Characteristic.human_attribute_name(:type_of_data)
      %th= Characteristic.human_attribute_name(:result_type)
      %th= Characteristic.human_attribute_name(:address)
      %th

  %tbody
    - @characteristics.each do |characteristic|
      %tr
        %td{:data => {:label => Characteristic.human_attribute_name(:name)}}
          = characteristic.name
        %td{:data => {:label => Characteristic.human_attribute_name(:information_system)}}
          = characteristic.information_system.name
        %td{:data => {:label => Characteristic.human_attribute_name(:type_of_data)}}
          = characteristic.type_of_data
        %td{:data => {:label => Characteristic.human_attribute_name(:result_type)}}
          = characteristic.result_type
        %td{:data => {:label => Characteristic.human_attribute_name(:address)}}
          = characteristic.address.name

        %td.right
          = link_to characteristic, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_characteristic_path(characteristic), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to  characteristic, :method => :delete,
          :data => { :confirm => t('buttons.confirm.characteristic_values') },
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/characteristics/new.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.characteristics.new')
= render 'form'
.row
  .col-md-6.col-centre
    = link_to t('helpers.submit.back'), characteristics_path, class: "btn btn-primary buttons"

app/views/characteristics/show.html.haml
%p#notice= notice

%table.table-striped.table-hover.table-style
  %thead
    %tr
      %th= Characteristic.human_attribute_name(:name)
      %th= Characteristic.human_attribute_name(:information_system)
      %th= Characteristic.human_attribute_name(:type_of_data)
      %th= Characteristic.human_attribute_name(:result_type)
      %th= Characteristic.human_attribute_name(:address)
      %th

  %tbody
    %tr
      %td{:data => {:label => Characteristic.human_attribute_name(:name)}}
        = @characteristic.name
      %td{:data => {:label => Characteristic.human_attribute_name(:information_system)}}
        = @characteristic.information_system.name
      %td{:data => {:label => Characteristic.human_attribute_name(:type_of_data)}}
        = @characteristic.type_of_data
      %td{:data => {:label => Characteristic.human_attribute_name(:result_type)}}
        = @characteristic.result_type
      %td{:data => {:label => Characteristic.human_attribute_name(:address)}}
        = @characteristic.address.name

.row
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.back'), characteristics_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.create'), edit_characteristic_path(@characteristic), class: "btn btn-primary buttons"