config/routes.rb
Rails.application.routes.draw do
  resources :characteristic_values
  resources :weights
  resources :part_of_characteristics
  resources :people
  resources :characteristics
  resources :information_systems do
    collection do
      get :main
    end
  end
  resources :addresses
  get 'welcome/load_from_json', as: :lfj
  root :to => 'information_systems#main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/information_system.rb
class InformationSystem < ApplicationRecord
  has_many :characteristics

  # This file is auto-generated from the current state of the database. Instead

  validates :name, presence: true, uniqueness: true


end

app/controllers/information_systems_controller.rb
class InformationSystemsController < ApplicationController
  before_action :set_information_system, only: [:show, :edit, :update, :destroy]

  # GET /information_systems
  # GET /information_systems.json
  def index
    @information_systems = InformationSystem.all
  end

  # GET /information_systems/1
  # GET /information_systems/1.json
  def show
  end

  # GET /information_systems/new
  def new
    @information_system = InformationSystem.new
  end
  def main

  end

  # GET /information_systems/1/edit
  def edit
  end

  # POST /information_systems
  # POST /information_systems.json
  def create
    @information_system = InformationSystem.new(information_system_params)

    respond_to do |format|
      if @information_system.save
        format.html { redirect_to @information_system, notice: 'Information system was successfully created.' }
        format.json { render :show, status: :created, location: @information_system }
      else
        format.html { render :new }
        format.json { render json: @information_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information_systems/1
  # PATCH/PUT /information_systems/1.json
  def update
    respond_to do |format|
      if @information_system.update(information_system_params)
        format.html { redirect_to @information_system, notice: 'Information system was successfully updated.' }
        format.json { render :show, status: :ok, location: @information_system }
      else
        format.html { render :edit }
        format.json { render json: @information_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information_systems/1
  # DELETE /information_systems/1.json
  def destroy
    @information_system.destroy
    respond_to do |format|
      format.html { redirect_to information_systems_url, notice: 'Information system was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information_system
      @information_system = InformationSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_system_params
      params.require(:information_system).permit(:name, :timezone)
    end
end

app/helpers/information_systems_helper.rb
module InformationSystemsHelper
end

app/views/information_systems/_form.html.haml
= form_for @information_system do |f|
  - if @information_system.errors.any?
    #error_explanation
      %h2= "#{pluralize(@information_system.errors.count, "error")} prohibited this information_system from being saved:"
      %ul
        - @information_system.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-3.col-centre
      = f.label :name
    .col-md-6.col-centre
      = f.text_field :name
  .row
    .col-md-3.col-centre
      = f.label :timezone
    .col-md-6.col-centre
      = f.text_field :timezone
  .my-hr
    %hr
  .row
    .col-md-6.col-centre
      = f.submit t('helpers.submit.submit'), class: "btn btn-primary buttons"

app/views/information_systems/edit.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.information_systems.edit')
= render 'form'

.row
  .col-md-3.col-centre
    = link_to t('helpers.submit.back'), information_systems_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre
    = link_to t('helpers.submit.show'), @information_system, class: "btn btn-primary buttons"

app/views/information_systems/index.html.haml
%table.table-striped.table-hover.table-style.table-responsive
  .col-md-3.col-sm-3
    %caption.new-obj.table-responsive
      = link_to new_information_system_path, class: 'btn btn-primary' do
        = fa_icon :plus
        = t('headers.information_systems.new')
  %thead.table-head
    %tr
      %th= InformationSystem.human_attribute_name(:name)
      %th= InformationSystem.human_attribute_name(:timezone)
      %th

  %tbody
    - @information_systems.each do |information_system|
      %tr
        %td{:data => {:label => InformationSystem.human_attribute_name(:name)}}
          = information_system.name
        %td{:data => {:label => InformationSystem.human_attribute_name(:timezone)}}
          = information_system.timezone
        %td.right
          = link_to information_system, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_information_system_path(information_system), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to  information_system, :method => :delete,
          :data => { :confirm => t('buttons.confirm.information_systems') },
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')
-# %h1 Listing information_systems
-#
-# %table
-#   %thead
-#     %tr
-#       %th Name
-#       %th Timezone
-#       %th
-#       %th
-#       %th
-#
-#   %tbody
-#     - @information_systems.each do |information_system|
-#       %tr
-#         %td= information_system.name
-#         %td= information_system.timezone
-#         %td= link_to 'Show', information_system
-#         %td= link_to 'Edit', edit_information_system_path(information_system)
-#         %td= link_to 'Destroy', information_system, method: :delete, data: { confirm: 'Are you sure?' }
-#
-# %br
-#
-# = link_to 'New Information system', new_information_system_path

app/views/information_systems/main.html.haml
Добро пожаловать!
= link_to 'Информационные системы', information_systems_path
= link_to 'Характеристики', characteristics_path
= link_to 'Адреса', addresses_path
= link_to 'Характеристика-значение', characteristic_values_path
= link_to 'Части характеристики', part_of_characteristics_path
= link_to 'Люди', people_path
= link_to 'Веса', weights_path
= link_to 'parse',lfj_path

app/views/information_systems/new.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.information_systems.new')

.row
  %hr.my-hr

= render 'form'
.row
  .col-md-6.col-centre
    = link_to t('helpers.submit.back'), information_systems_path, class: "btn btn-primary buttons"

app/views/information_systems/show.html.haml
%p#notice= notice
%table.table-striped.table-hover.table-style
  %thead.table-head
    %tr
      %th= InformationSystem.human_attribute_name(:name)
      %th= InformationSystem.human_attribute_name(:timezone)
      %th
%tbody
  %tr
    %td{:data => {:label => InformationSystem.human_attribute_name(:name)}}
      = @information_system.name
    %td{:data => {:label => InformationSystem.human_attribute_name(:timezone)}}
      = @information_system.timezone

.row
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.back'), information_systems_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.create'), edit_information_system_path(@information_system), class: "btn btn-primary buttons"