config/routes.rb
Rails.application.routes.draw do
  resources :characteristic_values
  resources :weights
  resources :part_of_characteristics
  resources :people
  resources :characteristics
  resources :information_systems do
    collection do
      get :main
    end
  end
  resources :addresses
  get 'welcome/load_from_json', as: :lfj
  root :to => 'information_systems#main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/characteristic_value.rb
class CharacteristicValue < ApplicationRecord
  belongs_to :part_of_characteristic
  belongs_to :person

    validates :value, presence: true
    validates :vdate, presence: true
    validates :vtime, presence: true

end

app/controllers/characteristic_values_controller.rb
class CharacteristicValuesController < ApplicationController
  before_action :set_characteristic_value, only: [:show, :edit, :update, :destroy]

  # GET /characteristic_values
  # GET /characteristic_values.json
  def index
    @characteristic_values = CharacteristicValue.all
  end

  # GET /characteristic_values/1
  # GET /characteristic_values/1.json
  def show
  end

  # GET /characteristic_values/new
  def new
    @characteristic_value = CharacteristicValue.new
  end

  # GET /characteristic_values/1/edit
  def edit
  end

  # POST /characteristic_values
  # POST /characteristic_values.json
  def create
    @characteristic_value = CharacteristicValue.new(characteristic_value_params)

    respond_to do |format|
      if @characteristic_value.save
        format.html { redirect_to @characteristic_value, notice: 'Characteristic value was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic_value }
      else
        format.html { render :new }
        format.json { render json: @characteristic_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristic_values/1
  # PATCH/PUT /characteristic_values/1.json
  def update
    respond_to do |format|
      if @characteristic_value.update(characteristic_value_params)
        format.html { redirect_to @characteristic_value, notice: 'Characteristic value was successfully updated.' }
        format.json { render :show, status: :ok, location: @characteristic_value }
      else
        format.html { render :edit }
        format.json { render json: @characteristic_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristic_values/1
  # DELETE /characteristic_values/1.json
  def destroy
    @characteristic_value.destroy
    respond_to do |format|
      format.html { redirect_to characteristic_values_url, notice: 'Characteristic value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic_value
      @characteristic_value = CharacteristicValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_value_params
      params.require(:characteristic_value).permit(:part_of_characteristic_id, :value, :person_id, :vdate, :vtime)
    end
end

app/helpers/characteristic_values_helper.rb
module CharacteristicValuesHelper
end

app/views/characteristic_values/_form.html.haml
= form_for @characteristic_value do |f|
  - if @characteristic_value.errors.any?
    #error_explanation
      %h2= "#{pluralize(@characteristic_value.errors.count, "error")} prohibited this characteristic_value from being saved:"
      %ul
        - @characteristic_value.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-3.col-centre
      = f.label :part_of_characteristic
    .col-md-6.col-centre
      = f.text_field :part_of_characteristic_id
  .row
    .col-md-3.col-centre
      = f.label :value
    .col-md-6.col-centre
      = f.text_field :value
  .row
    .col-md-3.col-centre
      = f.label :person
    .col-md-6.col-centre
      = f.text_field :person_id
  .row
    .col-md-3.col-centre
      = f.label :vdate
    .col-md-6.col-centre
      = f.date_select :vdate
  .row
    .col-md-3.col-centre
      = f.label :vtime
    .col-md-6.col-centre
      = f.time_select :vtime
  .my-hr
    %hr
  .row
    .col-md-6.col-centre
      = f.submit t('helpers.submit.submit'), class: "btn btn-primary buttons"

app/views/characteristic_values/edit.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.addresses.edit')
= render 'form'

.row
  .col-md-3.col-centre
    = link_to t('helpers.submit.back'), characteristic_values_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre
    = link_to t('helpers.submit.show'), @characteristic_value, class: "btn btn-primary buttons"

app/views/characteristic_values/index.html.haml
%table.table-striped.table-hover.table-style
  %caption.new-obj
    = link_to new_characteristic_value_path, class: 'btn btn-primary' do
      = fa_icon :plus
      = t('buttons.new.characteristic_values')
  %thead.table-head
    %tr
      %th= CharacteristicValue.human_attribute_name(:part_of_characteristic)
      %th= CharacteristicValue.human_attribute_name(:value)
      %th= CharacteristicValue.human_attribute_name(:person)
      %th= CharacteristicValue.human_attribute_name(:vdate)
      %th= CharacteristicValue.human_attribute_name(:vtime)
      %th

  %tbody
    - @characteristic_values.each do |characteristic_value|
      %tr
        %td{:data => {:label => CharacteristicValue.human_attribute_name(:part_of_characteristic)}}
          = characteristic_value.part_of_characteristic.part_name
        %td{:data => {:label => CharacteristicValue.human_attribute_name(:value)}}
          = characteristic_value.value
        %td{:data => {:label => CharacteristicValue.human_attribute_name(:person)}}
          = characteristic_value.person.pid
        %td{:data => {:label => CharacteristicValue.human_attribute_name(:vdate)}}
          = l(characteristic_value.vdate)
        %td{:data => {:label => CharacteristicValue.human_attribute_name(:vtime)}}
          = characteristic_value.vtime
        %td.right
          = link_to characteristic_value, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_characteristic_value_path(characteristic_value), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to  characteristic_value, :method => :delete,
          :data => { :confirm => t('buttons.confirm.characteristic_values') },
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/characteristic_values/new.html.haml
%h1.my-tit.row
  .col-md-12
    = t('headers.characteristic_values.new')

.row
  %hr.my-hr

= render 'form'
.row
  .col-md-6.col-centre
    = link_to t('helpers.submit.back'), characteristic_values_path, class: "btn btn-primary buttons"

app/views/characteristic_values/show.html.haml
%p#notice= notice

%table.table-striped.table-hover.table-style
  %thead.table-head
    %tr
      %th= CharacteristicValue.human_attribute_name(:part_of_characteristic)
      %th= CharacteristicValue.human_attribute_name(:value)
      %th= CharacteristicValue.human_attribute_name(:person)
      %th= CharacteristicValue.human_attribute_name(:vdate)
      %th= CharacteristicValue.human_attribute_name(:vtime)
      %th

  %tbody
    %tr
      %td{:data => {:label => CharacteristicValue.human_attribute_name(:part_of_characteristic)}}
        = @characteristic_value.part_of_characteristic.part_name
      %td{:data => {:label => CharacteristicValue.human_attribute_name(:value)}}
        = @characteristic_value.value
      %td{:data => {:label => CharacteristicValue.human_attribute_name(:person)}}
        = @characteristic_value.person.pid
      %td{:data => {:label => CharacteristicValue.human_attribute_name(:vdate)}}
        = @characteristic_value.vdate
      %td{:data => {:label => CharacteristicValue.human_attribute_name(:vtime)}}
        = @characteristic_value.vtime
.row
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.back'), characteristic_values_path, class: "btn btn-primary buttons"
  .col-md-3.col-centre.col-sm-6
    = link_to t('helpers.submit.create'), edit_characteristic_value_path(@characteristic_value), class: "btn btn-primary buttons"